name: CI
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      apptype:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    if: ${{ inputs.apptype == 'maven' }}
    steps:
       
      - uses: actions/checkout@v4
        
      - name: Build with Maven
        run: mvn clean package

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.apptype == 'maven' }}
        with:
          name: shipping-jar
          path: target/shipping-1.0.jar
  test:
    needs: build
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run ${{ inputs.apptype }} test
        run: echo ${{ inputs.apptype }} test
  docker:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u4j6q5s8
      - uses: actions/download-artifact@v4
        if: ${{ inputs.appName == 'maven' }}
        with:
          name: shipping-jar
          path: ./
      - name: build docker image
        run: docker build -t public.ecr.aws/u4j6q5s8/${{ inputs.appName }}:v1 .
      - name: push to aws ecr
        run: docker push public.ecr.aws/u4j6q5s8/${{ inputs.appName }}:v1

  dev:
    needs: docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          repository: pdevops87/roboshop-helm-v1
      - name: connect to kubernetes api through kubeconfig
        run:  aws eks update-kubeconfig --name dev
      - name: deploy app
        run:  helm upgrade -i ${{ inputs.appName }} -f pass-values-templates/${{ inputs.appName }}.yaml
      - name: argocd-server LB
        run: echo kubectl get svc argocd-server -o jsonpath="{.status.loadBalancer.ingress[*].hostname}"
      - name: argocd password
        run: echo kubectl get secrets argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode
      - name: argocd login
        run: argocd login $( kubectl get svc argocd-server -o jsonpath="{.status.loadBalancer.ingress[0].hostname}) --insecure --username admin --password $(kubectl get secrets argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)
      - name: create apps to argocd through cli
        run: argocd app create ${{ inputs.appName }} --repo https://github.com/pdevops87/roboshop-helm-v3-final.git   --path .   --dest-namespace default   --dest-server https://kubernetes.default.svc  --values pass-to-templates/${{ inputs.appName }}.yaml  --upsert










