name: CI
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      apptype:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    # Only run build if it's a maven app
    # if: ${{ inputs.apptype == 'maven' }}
    steps:
      - uses: actions/checkout@v4
        # if: ${{ inputs.apptype == 'maven' }}
      - name: Build with Maven
        if: ${{ inputs.apptype == 'maven' }}
        run: mvn clean package
      - name: upload artifact
        if: ${{ inputs.apptype == 'maven' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.appName }}-jar
          path: target/${{ inputs.appName }}-1.0.jar
      - name: ${{ inputs.appName }}
        if: ${{ inputs.apptype != 'maven' }}
        run: echo "${{ inputs.appName }}-cicd pipeline"
  test:
    needs: build
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run ${{ inputs.apptype }} test
        run: echo ${{ inputs.apptype }} test
  docker:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Docker Login with Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws sts get-caller-identity
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041445559784.dkr.ecr.us-east-1.amazonaws.com
        

        if: ${{ inputs.apptype == 'maven' }}
      - uses: actions/download-artifact@v4
        name: download artifact
        if: ${{ inputs.apptype == 'maven' }}
        with:
          name: ${{ inputs.appName }}-jar
          path:  .
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1



      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # This automatically outputs 041445559784.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ inputs.appName }}
          IMAGE_TAG: v1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
  dev:
    needs: docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          repository: pdevops87/roboshop-helm-v4-ingress

      - name: Connect to EKS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws eks update-kubeconfig --name dev-cluster --region us-east-1
          helm upgrade -i "${{ inputs.appName }}" . -f "pass-to-templates/${{ inputs.appName }}.yaml"
          
          
           ARGOCD_PASS=$(kubectl get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)
           echo "argocd password:${ARGOCD_PASS}"
           echo "Logging into ArgoCD..."
          
           argocd login argocd-dev.pdevops87.online \
             --insecure \
             --username admin \
             --password "$ARGOCD_PASS"
          
           echo "Creating application..."
          
           argocd app create "${{ inputs.appName }}" \
             --repo "https://github.com/pdevops87/roboshop-helm-v4-ingress.git" \
             --path . \
             --dest-namespace default \
             --dest-server https://kubernetes.default.svc \
             --values "pass-to-templates/${{ inputs.appName }}.yaml" \
             --upsert
          
           argocd app sync "${{ inputs.appName }}"
